import './globals.css'
import { Inter } from 'next/font/google'
<<<<<<< HEAD
import Header from './components/header'
import Footer from './components/footer'
=======
>>>>>>> 05ffb27 (Initial commit from Create Next App)

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
<<<<<<< HEAD
  title: 'Vlog App',
  description: 'Vlog App - Get Premium Modded App Courses Free On This Website',
=======
  title: 'Create Next App',
  description: 'Generated by create next app',
>>>>>>> 05ffb27 (Initial commit from Create Next App)
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
=======
      <body className={inter.className}>{children}</body>
>>>>>>> 05ffb27 (Initial commit from Create Next App)
    </html>
  )
}
